Platform refactoring
pointcloudtechnology/resumable.js pull request #1
Opened 2021-08-10 08:27 UTC by pawelsoundso

Rework the resumable files to be used inside the 3DPointHub project from PCT. This includes a transformation into JS CSS classes as well as the option to validate files with custom functions before adding them to the files list inside resumable.

2021-10-14 13:15 UTC, anne-gropler commented on src/resumableHelpers.js
> +        return seen.add(k);
I find it quite confusing to `return seen.add(k);`, because `Set.add(k)` returns the set (i.e. an object) after adding `k`.

Since this is inside a `filter` function, this returned set (object) is read as "truthy" and thus everything works, but it would be clearer to the human reader if we wrote this instead:
```suggestion
        seen.add(k);
        return true;
```

2021-10-14 13:21 UTC, anne-gropler commented on src/resumableHelpers.js
> +    }
Technically, if there is a `return` statement, we don't need `else`.

This is just a proposal, feel free to ignore it if you find the current version more readable :)

```suggestion
    if (size < 1024) {
      return size + ' bytes';
    }
    if (size < 1024 * 1024) {
      return (size / 1024.0).toFixed(0) + ' KB';
    }
    if (size < 1024 * 1024 * 1024) {
      return (size / 1024.0 / 1024.0).toFixed(1) + ' MB';
    }
    return (size / 1024.0 / 1024.0 / 1024.0).toFixed(1) + ' GB';
  }
```

2021-10-14 13:22 UTC, anne-gropler commented on src/resumableHelpers.js
> +   * @param {string}testTarget
nit-picking:
```suggestion
   * @param {string} testTarget
```

2021-10-14 15:07 UTC, pawelsoundso commented on src/resumableEventHandler.js
> +        this.fire('error', args[1], args[0]);
Okey: This is used to simulate the original version: The base version of Resumable always throws an `error`-event if `fileerror` is thrown. Keep in mind, that the event key is here definitely different. Thus, the same function should not arrive here again.

2021-11-04 10:53 UTC, adi64 requested changes

2021-11-04 10:53 UTC, adi64 commented on resumable.d.ts
> +     * The component that contains the current one and should be used to bubble up the event.
"The component that contains the current one"? :sweat_smile:

2021-11-04 10:53 UTC, adi64 commented on resumable.d.ts
> +    parent: Resumable | ResumableFile;
So if I understand this correctly, a `ResumableFile extends ResumableEventHandler` and `ResumableEventHandler` in turn can have a `ResumableFile` as parent? :thinking:

2021-11-04 10:53 UTC, adi64 commented on resumable.d.ts
> +    events: { string: function[] };
The description does not seem to fit to the actual type. The actual type looks like an object mapping each string to a list of functions. (?)

2021-11-04 10:53 UTC, adi64 commented on resumable.d.ts
> +    events: { string: function[] };
oh, it seems that an "event" is actually an event **name**, right?

2021-11-04 10:53 UTC, adi64 commented on resumable.d.ts
> +    events: { string: function[] };
So this is rather the list of registered event handlers for each event? In that case I think `events` is maybe not the best choice, maybe something like `registeredEventHandlers`?

2021-11-04 10:53 UTC, adi64 commented on src/resumableEventHandler.js
> +    this.events[event.toLowerCase()].push(callback);
`event` is already lowercase (see line 8) :wink:

2021-11-04 10:53 UTC, adi64 commented on src/resumableEventHandler.js
> +    console.log(this.constructor.name, event, args);
Is this still needed?

2021-11-04 10:53 UTC, adi64 commented on src/resumableEventHandler.js
> +    this.executeEventCallback('*', event, ...args);
So if something wants to be notified of *all* events that are fired, here an additional "meta"-event is fired, so to say? (Just checking if I understand this correctly)

2021-11-04 10:56 UTC, adi64 commented on resumable.d.ts
> +     * The component that contains the current one and should be used to bubble up the event.
ah, that contains *this* instance. I see.

2021-11-04 13:18 UTC, UniquePanda commented on src/resumableEventHandler.js
> +        this.fire('error', args[1], args[0]);
I'd like to have that explanation in the code as a comment, too :D  
Something like `For some specific events, additional more general events are fired`

2021-11-04 13:20 UTC, UniquePanda commented on src/resumableEventHandler.js
> +
```suggestion
```

2021-11-04 13:26 UTC, UniquePanda commented on src/resumable.js
> +      fileType: this.fileType = [],
Shouldn't this be called `fileTypes`?

2021-11-04 13:26 UTC, adi64 commented on src/resumableChunk.js
> +      this.endByte = this.fileObjSize;
I think our backend does not support that. As far as I know we have assertions in place that every chunk is smaller or equal to the `chunkSize`.

Therefore, I think we could remove the whole `forceChunkSize` parameter :thinking:

2021-11-04 13:26 UTC, adi64 commented on src/resumableChunk.js
> +          this.resumableObj.uploadNextChunk();
If the status is `error` - which is a **permanent** error, if I understand this correctly - we still trigger uploading the next chunk? Why?

2021-11-04 13:28 UTC, UniquePanda commented on src/resumable.js
> +      },
```suggestion
      fileValidationErrorCallback: this.fileValidationErrorCallback = (file) => {},
```

2021-11-04 13:30 UTC, UniquePanda commented on src/resumable.js
> +   * @param {Object} item item to upload, may be file or directory entry
```suggestion
   * @param {Object} item item to upload, may be a file or directory entry
```

2021-11-04 13:55 UTC, UniquePanda commented on src/resumable.js
> +      if (this.files.some((addedFile) => addedFile.uniqueIdentifier === file.uniqueIdentifier)) {
I think this should be called first (before assigning `fileType` and `fileExtension`)

2021-11-04 14:00 UTC, UniquePanda commented on src/resumable.js
> +          this.fileTypeErrorCallback(file, errorCount++);
I am not sure, what exactly error count is and how it is used in the callback.  
But if `errorCount` is `1` this will call the callback with `1` and increment the count **afterwards**. So if this was the second error, the callback might think it was the first one? (Same for other increments of `errorCount` below)

2021-11-04 14:00 UTC, UniquePanda commented on src/resumable.js
> +          this.fileTypeErrorCallback(file, errorCount++);
Probably `++errorCount` would be better

2021-11-04 14:02 UTC, UniquePanda commented on src/resumable.js
> +          this.fileTypeErrorCallback(file, errorCount++);
Actually.. I can't find the place where `errorCount` is even defined? 😅

2021-11-04 14:14 UTC, UniquePanda commented on src/resumable.js
> +          this.fileTypeErrorCallback(file, errorCount++);
From looking at the code again, I think you just have to know that the first callback always gets error count 0, the second gets 1 and so on. I guess this works.  
But you definitely forgot to add something like `let errorCount = 0`

2021-11-04 15:09 UTC, adi64 commented on src/resumableFile.js
> +  }
After discussing with Marcel, I now understand that this is using **destructuring assignment** while binding to object properties. Holy cow :D Could you please add a little comment here? I was *really* lost :sweat_smile:

2021-11-04 15:13 UTC, adi64 commented on src/resumable.js
> +    this.opts = options;
So the `options` are assigned to individual properties of this object, but also duplicated to the `opts` object? I could only find one usage where the total `opts` object is passed down to another class. Could we de-duplicate this somehow?

2021-11-04 15:14 UTC, adi64 commented on src/resumable.js
> +        alert(`${file.fileName || file.name} has type not allowed, please upload files of type ${this.fileType}.`);
```suggestion
        alert(`${file.fileName || file.name} has an unsupported file typ, please upload files of type ${this.fileType}.`);
```

2021-11-05 08:58 UTC, anne-gropler commented on resumable-tests.ts
>  let {} = resumable.getFromUniqueIdentifier('test');
In the meantime, have you found out? I couldn't find anything about this. I mean, this is strange syntax, so I guess it is some js magic?
How can a variable be defined with `let` but without a name? Is this some kind of destructuring? But the properties of the resulting `ResumableFile` object (like `chunks`, `relativePath`, ...) are not used later on as far as I can see.

Ok, enough speculation... it's just tests, so I guess it is ok to keep it like the original.

2021-11-16 10:32 UTC, pawelsoundso commented on src/resumableEventHandler.js
> +    this.executeEventCallback('*', event, ...args);
Yes this is called a "wildcard" event that can be used to catch any events thrown.

2021-11-16 10:55 UTC, pawelsoundso commented on src/resumable.js
> +      if (this.files.some((addedFile) => addedFile.uniqueIdentifier === file.uniqueIdentifier)) {
Gladly, I didn't really matter until now as it returned inside the conditional, but I moved it further up nonetheless.

2021-11-16 11:45 UTC, pawelsoundso commented on src/resumable.js
> +          this.fileTypeErrorCallback(file, errorCount++);
As this variable seems to be unused, also inside the default function, I removed it completely.

2021-11-16 11:46 UTC, pawelsoundso commented on src/resumableFile.js
> +    this._prevProgress = 0;
Historically, underscored variable names were used to declare private attributes in JS. I assume this is also the case here.

2021-11-18 09:22 UTC, anne-gropler commented on src/resumable.js
> +  }
I see that you renamed it to `mapItemToFile`, I like that.

2022-03-02 15:39 UTC, pawelsoundso commented on README.md
> +* `.catchAll(event, ...)` Listen to all the registered event handlers listed above with the same callback function.
It should be changed now

2022-03-03 11:29 UTC, adi64 requested changes

2022-03-03 14:13 UTC, pawelsoundso commented on src/resumableChunk.ts
> +      this.endByte = this.fileObjSize;
I removed it now

2022-03-03 15:13 UTC, anne-gropler approved these changes

2022-03-03 15:13 UTC, merged