Add CHANGELOG.md
pointcloudtechnology/resumable.js pull request #22
Opened 2024-02-03 13:15 UTC by UniquePanda

This adds a CHANGELOG.md to the project.
I already added changelog entries for all existing releases.

2024-02-04 09:36 UTC, williamdes approved these changes

2024-02-05 08:14 UTC, adi64 requested changes

2024-02-05 08:14 UTC, adi64 commented on CHANGELOG.md
> +Starting with version `2.1.0` all changes will be added via proper smaller PRs.
I can understand what you want to say with this, but I'd say the Changelog is the wrong place for this.
Also, this kind of takes the possibility away of a larger refactoring :p
I'd just remove these two lines.

2024-02-05 10:48 UTC, UniquePanda commented on CHANGELOG.md
> +Starting with version `2.1.0` all changes will be added via proper smaller PRs.
Done

2024-02-05 10:50 UTC, adi64 approved these changes

2024-02-05 10:50 UTC, merged