Add optional verbose logging
pointcloudtechnology/resumable.js pull request #27
Opened 2024-02-06 11:09 UTC by UniquePanda

**Merge after #25**

# Long description

This adds a new constructor option for the main resumable class.
The new option `debugVerbosityLevel` can either be 0, 1, 2 (or the respective enum values `DebugVerbosityLevel.NONE`, `DebugVerbosityLevel.LOW` and `DebugVerbosityLevel.HIGH`).
If it is `DebugVerbosityLevel.NONE`, no debug logging is done at all.
If it is `DebugVerbosityLevel.LOW`, some debug logging is done. This should be sufficient to find most problems.
If it is `DebugVerbosityLevel.HIGH`, all debug logs are written. This can help for example if there is a problem somewhere in the communication between different resumable classes.

# TODOs

* [x] I ran npm run build and pushed the dist files if needed
* [ ] I added an entry to the CHANGELOG.md for this PR

2024-02-11 13:44 UTC, williamdes approved these changes

2024-02-12 10:09 UTC, adi64 requested changes

2024-02-12 10:09 UTC, adi64 commented on src/resumable.ts
>        this.uploadNextChunk();
To debug here, I'd appreciate a message indicating the current "worker number", e.g.

```suggestion
    for (let num = 1; num <= this.simultaneousUploads; num++) {
      Helpers.printDebugHigh(this.debugVerbosityLevel, 'Starting simultaneous upload ' + String(num) + ' / ' + String(this.simultaneousUploads) + ' ...');
      this.uploadNextChunk();
```

2024-02-12 10:09 UTC, adi64 commented on src/resumableChunk.ts
> +    Helpers.printDebugLow(this.debugVerbosityLevel, 'Constructing ResumableChunk...');
same as with `Resumable` constructor

2024-02-12 10:09 UTC, adi64 commented on src/resumableFile.ts
> +    Helpers.printDebugLow(this.debugVerbosityLevel, 'Constructing ResumableFile...');
Same as Resumable constructor.

2024-02-12 14:39 UTC, UniquePanda commented on src/resumable.ts
> +    Helpers.printDebugLow(this.debugVerbosityLevel, 'Constructing Resumable...');
True!
I removed it here and in the other constructors.
I also removed the `Setting instance properties...` log messages which were placed before `Object.assign(this, options)` and therefore also never printed! 😄

2024-02-12 14:39 UTC, UniquePanda commented on src/resumableChunk.ts
> +    Helpers.printDebugLow(this.debugVerbosityLevel, 'Constructing ResumableChunk...');
Removed (see response for Resumable constructor)

2024-02-12 14:39 UTC, UniquePanda commented on src/resumableFile.ts
> +    Helpers.printDebugLow(this.debugVerbosityLevel, 'Constructing ResumableFile...');
Removed (see response for Resumable constructor)

2024-02-12 14:39 UTC, UniquePanda commented on src/resumable.ts
>        this.uploadNextChunk();
Done. I removed the `String()` casts, because the numbers are just simple ints and we're still doing Javascript! 😝 
![image](https://github.com/pointcloudtechnology/resumable.js/assets/3686982/4b698d50-ec35-48aa-9c11-91887c05fc99)

I additionally added a corresponding `Started simultaneous upload` message after the call to `uploadNextChunk()`.

2024-02-15 10:52 UTC, adi64 approved these changes

2024-02-15 10:52 UTC, merged